server:
  port: 8080
  host: 0.0.0.0


tracing:
    service: "helidon-full-http"
    protocol: "http"     # JAEGER_ENDPOINT (if not udp, http is expected and endpoint is filled)
    host: "localhost"   # JAEGER_ENDPOINT
    port: 14250           # JAEGER_ENDPOINT
    path: "/api/traces/mine"   # JAEGER_ENDPOINT
    propagation: "jaeger" # JAEGER_PROPAGATION either "jaeger" or "b3"
    log-spans: false      # JAEGER_REPORTER_LOG_SPANS
    max-queue-size: 42    # JAEGER_REPORTER_MAX_QUEUE_SIZE
    sampler-type: "const"# JAEGER_SAMPLER_TYPE (https://www.jaegertracing.io/docs/latest/sampling/#client-sampling-configuration)
    sampler-param: 1    # JAEGER_SAMPLER_PARAM (number)

app:
  greeting: "Hello"


